print("Second Half Action")
print("==================")
Hhs = int(input("enter the home team half time score:"))
Ahs = int(input("enter the away team half time score:"))
print("")
Hfs = int(input("enter the home team full time score:"))
Afs = int(input("enter the home team full time score:"))
print("")
print("The total number of goals scored after half time is: " + str((Hfs + Afs) - (Hhs + Ahs)) + " goals")